export const ROOT_URL = process.env.REACT_APP_BASE_ENV === "production" ? process.env.REACT_APP_BASE_URL : 'http://localhost:5000';
export const AUTHENTICATED = 'authenticated_user';
export const UNAUTHENTICATED = 'unauthenticated_user';
export const AUTHENTICATED_ERROR = 'authenticated_error';
export const REGISTER = 'register_user';
export const USER_ALREADY_EXISTS = 'user_already_exists';
export const FETCH_CATEGORIES = 'fetch_categories';
export const FETCH_CATEGORY = 'fetch_category';
export const FETCH_CATEGORY_RECIPES = 'fetch_category_recipes';
export const FETCH_RECIPES = 'fetch_recipes';
export const FETCH_RECIPE = 'fetch_recipe';
export const CREATE_CATEGORY = 'create_category';
export const CREATE_RECIPE = 'create_recipe';
export const DELETE_RECIPE = 'delete_recipe';
export const EDIT_RECIPE = 'edit_recipe';
export const IS_LOADING = 'is_loading';
export const NOT_LOADING = 'not_loading';
